version: "3.7"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - default-bridge

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - default-bridge

  buddies_back:
    build:
      context: ./BuddyBridge_BE
      dockerfile: Dockerfile.local
    container_name: buddies_back
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./BuddyBridge_BE:/usr/app
    networks:
      - default-bridge

  buddies_front:
    build:
      context: ./BuddyBridge_FE
      dockerfile: Dockerfile.local
    container_name: buddies_front
    ports:
      - "3001:3000"
    depends_on:
      - buddies_back
    volumes:
      - ./BuddyBridge_FE/src:/usr/app/src
    networks:
      - default-bridge      

volumes:
  mariadb_data:
    driver: local

networks:
  default-bridge:
    name: dev-net
